[package]
name = "rohanasan"
version = "0.1.2"
edition = "2021"
description="Rohanasan: An extremely fast backend framework for rust!"
license="MIT"
repository="https://github.com/rohanasan/rohanasan-rs"
categories = ["web-programming::http-server"]
authors = ["Rohan Vashisht"]
readme = "README.md"

[dependencies]
libc = "0.2.153"
