[package]
name = "rohanasan"
version = "0.1.2"
edition = "2021"
description="Rohanasan-rs: an extremely fast backend framework for rust!"
license="MIT"
repository="https://github.com/rohanasan/rohanasan-rs"

[dependencies]
libc = "0.2.153"
